server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # naglowki, ktore script.js odczyta przy kazdym odswiezeniu strony
    add_header X-Server-IP $server_addr;
    add_header X-Server-Hostname $hostname;

    # wylaczenie pamieci podrecznej (zawsze aktualne dane)
    add_header Cache-Control "no-store, no-cache, must-revalidate";

    location / {
        try_files $uri $uri/ =404;
    }
}